-- AlterTable
ALTER TABLE "posts" ALTER COLUMN "post" DROP NOT NULL,
ALTER COLUMN "href" DROP NOT NULL,
ALTER COLUMN "published" DROP NOT NULL,
ALTER COLUMN "published" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "published" SET DATA TYPE TIMESTAMP(6);
